#!/usr/bin/env bash

word=${1:-$(xclip -o -selection primary 2>/dev/null || wl-paste 2>/dev/null)}

# If nothing selected, prompt the user
if [[ -z "$word" ]]; then
	word="$(printf '' | rofi -dmenu -p 'Word:')"
fi

lang=$(language_detect.sh "$word")

# Check for empty word or special characters
# [[ -z "$word" || "$word" =~ [\/] ]] && notify-send -h string:bgcolor:#bf616a -t 3000 "Invalid input." && exit 0

if [[ "$lang" = "English" ]]; then

	query=$(curl -s --connect-timeout 5 --max-time 10 "https://api.dictionaryapi.dev/api/v2/entries/en_US/$word")

	# Check for connection error (curl exit status stored in $?)
	[ $? -ne 0 ] && notify-send -h string:bgcolor:#bf616a -t 3000 "Connection error." && printf '' | xclip -i -selection primary && exit 1

	# Check for invalid word response
	[[ "$query" == *"No Definitions Found"* ]] && notify-send -h string:bgcolor:#bf616a -t 3000 "Invalid word." && exit 0

	# Show only first 3 definitions
	def=$(echo "$query" | jq -r '[.[].meanings[] | {pos: .partOfSpeech, def: .definitions[].definition}] | .[:3].[] | "\n\(.pos). \(.def)"')

	# Requires a notification daemon to be installed
	notify-send -t 60000 "$word -" "$def"
	printf '' | xclip -i -selection primary # Explicitly clear primary, this is so it doesn't keep showing the same definition of the word

else
	if [-d $HOME/IDENTIFIER/THIS/IS/MOM/]; then
		firefox "moz-extension://8e5a32da-2c7e-4ec1-a899-1a52686ecf96/search.html?query=$word"
	else
		firefox "moz-extension://e687bdd9-e8cd-402d-9465-2f787c0e7492/search.html?query=$word"
	fi

	printf '' | xclip -i -selection primary # Explicitly clear primary, this is so it doesn't keep showing the same definition of the word
fi

### MORE OPTIONS :)

# Show first definition for each part of speech (thanks @morgengabe1 on youtube)
# def=$(echo "$query" | jq -r '.[0].meanings[] | "\(.partOfSpeech): \(.definitions[0].definition)\n"')

# Show all definitions
# def=$(echo "$query" | jq -r '.[].meanings[] | "\n\(.partOfSpeech). \(.definitions[].definition)"')

# Regex + grep for just definition, if anyone prefers that to jq
# def=$(grep -Po '"definition":"\K(.*?)(?=")' <<< "$query")

# bold=$(tput bold) # Print text bold with echo, for visual clarity
# normal=$(tput sgr0) # Reset text to normal
# echo "${bold}Definition of $word"
# echo "${normal}$def"
