#!/usr/bin/env bash
#   █████╗ ██████╗ ██████╗ ███████╗    ██╗      █████╗ ██╗   ██╗███╗   ██╗ ██████╗██╗  ██╗███████╗██████╗
#  ██╔══██╗██╔══██╗██╔══██╗██╔════╝    ██║     ██╔══██╗██║   ██║████╗  ██║██╔════╝██║  ██║██╔════╝██╔══██╗
#  ███████║██████╔╝██████╔╝███████╗    ██║     ███████║██║   ██║██╔██╗ ██║██║     ███████║█████╗  ██████╔╝
#  ██╔══██║██╔═══╝ ██╔═══╝ ╚════██║    ██║     ██╔══██║██║   ██║██║╚██╗██║██║     ██╔══██║██╔══╝  ██╔══██╗
#  ██║  ██║██║     ██║     ███████║    ███████╗██║  ██║╚██████╔╝██║ ╚████║╚██████╗██║  ██║███████╗██║  ██║
#  ╚═╝  ╚═╝╚═╝     ╚═╝     ╚══════╝    ╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
# Script to control prefered apps to launch for all themes
# Author: z0mbi3
# url:    https://github.com/gh0stzk

WIDGET_DIR="$HOME/.config/bspwm/eww"

case "$1" in
    --rice)
        RiceSelector
        ;;
    --update)
        $TERMINAL --hold --class FloaTerm,FloaTerm -o window.dimensions.lines=22 window.dimensions.columns=90 -e Updates --update-system
        ;;
    --checkupdates)
        $TERMINAL --hold --class Updating,Updating -o window.dimensions.lines=22 window.dimensions.columns=47 -e Updates --print-updates
        ;;
    --ranger)
	if [ "$TERMINAL" = "alacritty" ]; then
		$TERMINAL --class FloaTerm,FloaTerm -o window.dimensions.lines=14 window.dimensions.columns=90 -e ranger
	else

	$TERMINAL -e ranger

	fi
        ;;
    --nvim)
        (cd ~/Desktop/Linux-Machine/; $TERMINAL -e nvim)
        ;;
    --fetch)
        $TERMINAL --hold --class FloaTerm,FloaTerm -o window.dimensions.lines=26 window.dimensions.columns=40 -e ~/.local/bin/sysfetch
        ;;
        # Apps
    --filemanager)
        thunar
        ;;
    --browser)
	$BROWSER
        ;;
    --obsidian)
        obsidian
        ;;
    --telegram)
        telegram-desktop
        ;;
    --whats)
        whatsapp-nativefier --disable-gpu
        ;;
    --soundcontrol)
        pavucontrol
        ;;
        # Eww Widgets
    --powermenu)
        eww -c "$WIDGET_DIR" open --toggle powermenu
        ;;
    --usercard)
        eww -c "$WIDGET_DIR" open --toggle launchermenu
        ;;
    --player)
        eww -c "$WIDGET_DIR" open --toggle music
        ;;
    --calendar)
        eww -c "$WIDGET_DIR" open --toggle date
        ;;
    *)
        echo "Invalid Option"
        ;;
esac
