#!/bin/bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find $PROGRAMMING_DIR $XDG_CONFIG_HOME $PROGRAMMING_DIR/Pwnable.kr $PROGRAMMING_DIR/Pwnable.kr/Toddlers_Bottle $PROGRAMMING_DIR/Pwnable.kr/Rookiss $PROGRAMMING_DIR/University~/ -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
