require('options')
require('misc')
require('keybindings')

require('plugins.lazy')
require('plugins.misc')
require('plugins.lualine')
require('plugins.tele')
require('plugins.treesitter')
require('plugins.lsp')
require('plugins.trouble')
require('plugins.zenmode')
require('plugins.harpoon')
require('plugins.oil')
require('plugins.noice')
require('plugins.vimtex')
require('plugins.obsidian')
require("plugins.surround")

