require("options")
require("keybindings")
require("autocommands")

require("plugins.lazy")
require("plugins.formatter")
require("plugins.lualine")
require("plugins.tele")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.trouble")
require("plugins.zenmode")
require("plugins.harpoon")
require("plugins.oil")
require("plugins.noice")
require("plugins.vimtex")
require("plugins.surround")
require("plugins.obsidian")
